# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 520f472f9f2160c9e6586838790c5402bf5b73a7e71eecd4a7f8168cf9c86d991769dfcf0be76534f4bb98490b4955fc8aa5d14902b5837c2634595f9b0af6ea

test:
  secret_key_base: 5b13a1be57fc923af08e480bff8c00e81db177c82fa10eeb2ea1c6564b05692295cde68c09cf512bbf1669b0ce574939278a053b72627ec56158e1f3105a3e77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
